baseURL = ""
title = "Code Combat"
# for smart copyright line, leave this blank and check [params.copyright]
copyright = ""
#languageCode = "en-us"
#metaDataFormat = "json"

theme = "minimo"


#googleAnalytics = "UA-7131036-4"

#pluralizeListTitles = false


disqusShortname = ""
googleAnalytics = ""

Paginate = 10
preserveTaxonomyNames = true

enableRobotsTXT = true # generate robots.txt

# Syntax Highlighting ( https://gohugo.io/content-management/syntax-highlighting/ )
pygmentsCodefences = true

enableEmoji = true

# Missing translations will default to this content language
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = "true"

[params.info]
description = "JavaScript Solutions"
title404 = "Nothing's here!"

[params.assets]
#favicon = "favicon.ico"
customCSS = ["css/custom.css"]
customJS = ["js/custom.js"]
gopher = "" # used in 404 template ( Generator: https://gopherize.me )

[params.copyright]
prefix = ""
holder = "luik"
startYear = "2018"
suffix = ""

[params.settings]
# date & time format: https://golang.org/pkg/time/
dateFormat = "2006, Jan 02"
listDateFormat = "2006, Jan 02"
archiveDateFormat = "Jan 02"
hideEntryNavigation = ["page"] # boolean / array of sections
showReadingTime = true
showLastmod = true
taxonomyCloudShuffle = true
accentColor = "#ffcd00"
hideMainMenu = false

[params.sidebar]
enable = true

[params.widgets]
homepage = ["recent_posts"]
sidebar = ["about","search","recent_posts","taxonomy_cloud"]
footer = ["social_menu"]

[params.opengraph.facebook]
admins = [] # array of Facebook IDs
appID = ""
pageID = ""

[params.opengraph.twitter]
page = "" # Twitter page username

[params.seo]
# Title Separator: - – — · • * ⋆ | ~ « » < >
titleSeparator = "•"

[params.social]
github = "LukaszSarzynski/CodeCombat-solutions"

[params.comments]
enable = false

# Isso: https://posativ.org/isso/
[params.comments.isso]
enable = false
scriptSrc = "" # "https://isso.example.com/js/embed.min.js"
dataAttrs = "" # "data-isso='https://isso.example.com' data-isso-require-author='true'"

[params.comments.staticman]
enable = false
apiEndpoint = "https://api.staticman.net/v2/entry"
maxDepth = 2

[params.comments.staticman.github]
username = "LukaszSarzynski"
repository = "CodeCombat-solutions"
branch = "master"

# Utterances: https://utteranc.es
[params.comments.utterances]
enable = false
issueTerm = "pathname" # pathname / url / title

[params.comments.utterances.github]
username = "LukaszSarzynski"
repository = "CodeCombat-solutions"

[params.search]
client = "fuse" # algolia / fuse / lunr

[params.search.algolia]
appId = ""
indexName = ""
searchApiKey = ""

[taxonomies]
tag = "tags"
#author = "authors"
#category = "categories"
#series = "series"


[permalinks]
page = "/:slug/"

[[menu.main]]
name = "Author"
weight = -10
identifier = "author"
url = "/"

[[languages.pl.menu.main]]
name = "Autor"
weight = -10
identifier = "author"
url = "/"

[blackfriday]
hrefTargetBlank = true

[languages]
# edit this block for your own language
[languages.en]
lang = "en"
contentDir = "content/english"
languageName = "English"
weight = 1

[languages.pl]
lang = "pl"
contentDir = "content/polish"
languageName = "Polski"
weight = 2



[imaging]
# See https://github.com/disintegration/imaging
# CatmullRom is a sharp bicubic filter which should fit the docs site well with its many screenshots.
# Note that you can also set this per image processing.
resampleFilter = "CatmullRom"

# Default JPEG quality setting. Default is 75.
quality = 98

anchor = "smart"